apiVersion: v1
kind: Service
metadata:
  name: simple-server-service
spec:
  selector:
    app: simple-server-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  