- name: Simple lab playbook
  hosts: lab
  become: yes
  tasks:
    - name: Call queen
      zad2:
        type: "queen"
        value: "{{ lookup('ansible.builtin.template', 'makro.j2', template_vars={'n': 3}) | trim | int }}"
      register: zad2_result

    - debug:
        var: zad2_result
