apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-server
  labels:
    app: fib-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fib-server
  template:
    metadata:
      name: fib-server
      labels:
        app: fib-server
    spec:
      containers:
        - name: fib-server
          image: fib-server:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 3
      restartPolicy: Always
      