apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deployment
  template:
    metadata:
      name: python-deployment
      labels:
        app: python-deployment
    spec:
      containers:
        - name: python-deployment
          image: python-server:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: job-results-pvc

      